### ISSUE TITLE
Overall Domain View

### ISSUE THREAD

**Issue by meryllblanchet** [adobe/franklin-dashboard#2]
As a dashboard user, I want to be able to:

- See and browse the list of top domains I am entitled to
- Configure how many domains I want to see and browse (10 - 25 - 50 - all)
- Configure a time period for the reporting (last 30 days, last 60 days, last 90 days, since ever)
- For each domain, see the average CWV values (LCP, FID, CLS) across all pages
- For each domain, see the distribution rate of green / orange / red CWV values across all pages 
- For each domain, see the trend to previous time period if applicable: improved CWV, similar CWV, degraded CWV
- For each domain, click on the domain name to switch to the Domain Pages view (see #3 )

**Comment by MarquiseRosier** [comment]
This is nearly done @meryllblanchet please visit and type in domainkey, and use a Franklin project like www.bamboohr.com for example to see this view; what's left is a trend line; we will add a button to the view that leads to some charting. 

This will be decorated more, and made much more beautiful; for now this is bare bones fulfilling the requirement.

https://datalist--franklin-dashboard--adobe.hlx.page

**Comment by langswei** [comment]
Dashboard deprecated, closing issue.
