### ISSUE TITLE
List block adjustments

### ISSUE THREAD

**Issue by langswei** [adobe/franklin-dashboard#29]
In conjunction with #28 there are some improvements which can be made to the list block including:
- replace good/okay/bad with good/needs improvement/poor terminology used by Google.  Add a link somewhere to https://web.dev/vitals/#core-web-vitals as a reference
- Average scores will be misleading for some customers.  I'm thinking median will give us less outlier impact but we can discuss the most useful data point.  Will require query changes.
- Unclear if the tri-color bar is for LCP, all CWVs blended, or what.  Please advise.

**Comment by MarquiseRosier** [comment]
Tri Color Bar is the average of all of the averages! The averages tell you what percentage of requests are green, red, yellow. 

The text on the head row reads "% of visits with good, okay, or bad CWV scores"

**Comment by MarquiseRosier** [comment]
the four columns after provide the actual scores and an idea of what's giving bad CWV performance.

**Comment by langswei** [comment]
Adjusted header labels with #31.

The note about average scores is actually more related to helix-run-query and not franklin-dashboard.  It turns out avg means 75th percentile per https://github.com/adobe/helix-run-query/blob/main/src/queries/rum-dashboard.sql#L494, so the original comments in this issue about outliers are not relevant.

Marquise answered the question about tri-color bar above.  In general a dashboard visitor will see more orange/red and their eyes will move to the right for a breakdown to have a better idea of areas to investigate.

Closing this issue.
