### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by meryllblanchet** [adobe/franklin-dashboard#5]
As a dashboard user, I want to be able to authenticate to the dashboard to view my websites data.
For that, I need to provide:

- my email address
- the domain I want to look at, or a wildcard in case I am entitled to look at several domains
- The authorization token to access the RUM data

**Comment by MarquiseRosier** [comment]
I think #7 might be an excellent for this :)

**Comment by langswei** [comment]
We don't store the unencrypted domainkey anywhere.  Unclear to me how we would build links that contain it.

The way domainkeys currently work is they are valid for one domain, or all domains.  There is no notion of a domainkey which provides access to several domains but not all.

**Comment by langswei** [comment]
> Unclear to me how we would build links that contain domainkey.

I remember a discussion with Lars along the lines of the sidekick could generate a new 30-day key for a requested report view for a given domain.  Seems doable however the act of creating the domainkey in the first place requires a post from an authorized domainkey.  Given most code is in public repos, we would need to figure out a way to not publish the authorized domainkey which I suppose would act as a service account.

**Comment by MarquiseRosier** [comment]
We use domainkey to authenticate; and it must be user provided at Launcher page created by @langswei
