### ISSUE TITLE
Report ideas

### ISSUE THREAD

**Issue by trieloff** [adobe/franklin-dashboard#6]
Some reports we can build with the data we have right now:
- Benchmarking: Exceptional Experience Score (how do you compare against other sites{
- Troubleshooting: Top missing pages (404 checkpoint URLs)
- Troubleshooting: Top top JS error sources (error checkpoint sources targets)
- Vanity: Page views over time

**Comment by solaris007** [comment]
@trieloff please provide individual queries / endpoint requests for the above for quick integration.

**Comment by langswei** [comment]
Dashboard deprecated, closing issue.
