### ISSUE TITLE
Consolidate sources, for same 404 URL

### ISSUE THREAD

**Issue by MarquiseRosier** [adobe/franklin-dashboard#66]
On Dashboard 404 Report, some rows contain same 404 URL with different sources. To better express that there are multiple sources, or duplicate 404 URLs, consolidate them and have a drop down that lists all the remaining sources of a 404. 

In the image below, www.adobe.com/us shows up 3 separate times with different sources.

![Screenshot 2024-01-31 at 2 48 55 PM](https://github.com/adobe/franklin-dashboard/assets/12217245/096b348c-0519-4105-a089-0f958d552f4a)

**Comment by langswei** [comment]
@ekremney This relates to your observation at https://cq-dev.slack.com/archives/C04MQCRHLBY/p1710254256141179.  I think there are a few ways to approach.

The current approach is that the count is based on the unique source, not the unique URL.  The URL displayed is simply the most common URL for a given source, but does not necessarily 100% of the cause for that source.

Marquise gave one alternative above, which may or may not be related to my proposal at https://cq-dev.slack.com/archives/C04MQCRHLBY/p1710258485152209?thread_ts=1710254256.141179&cid=C04MQCRHLBY which is to use a different query altogether, less oriented around the source.

Ultimately this is a question of grouping by 404 URL or grouping by source.  Given the page is named 404 Report, in my mind (without having tested) it is more intuitive to group by 404 URL.

@MarquiseRosier WDYT?

**Comment by MarquiseRosier** [comment]
@langswei I think grouping is not useful; but maybe just combining the records and having drop down; 

You're right; since the recommended course of action is to fix the 404 by either redirect, or by fixing the actual page, server, etc, 

It doesn't quite matter where the 404 is (source), but I think it is significant to have an idea of damage...or how widespread a 404 is impacting; so maybe if we don't have sources, we aggregate them into some kind of count; like source_count :) 

@langswei

**Comment by langswei** [comment]
Sounds good @MarquiseRosier.  I will work on a new run-query optimized for this view since our current library of run-queries does not offer this.

Which would you prefer?  The decision here will drive what we can show on the UI.
Option 1: return url (string), top_source (string), source_count (int), and views (int)
Option 2: return url (string), sources (array of strings), and views (int)
Option 3: return url (string), sources (array of json which includes both source and source_views), and views (int)

**Comment by MarquiseRosier** [comment]
Nice; hmmmm, I think number 1 is enough! It doesn't matter the source really; as long as they know the url, they can fix it only two ways! 

I think the source_count is all we need!

**Comment by langswei** [comment]
New run-query`@v3/rum-404` addresses the issue, need to swap out `rum-sources` and swap in this new one to dashboard.
