### ISSUE TITLE
Add Stacked Bar Chart for subdomains that make up pageview chart aggregated views!

### ISSUE THREAD

**Issue by MarquiseRosier** [adobe/franklin-dashboard#95]
<img width="1467" alt="Screenshot 2024-04-15 at 8 53 05 PM" src="https://github.com/adobe/franklin-dashboard/assets/12217245/b09664c1-ab58-440a-a49c-7ab7b9ae1383">

Not enough details in this image; to explain what subdomains might be accounting for the traffic shown here. Give more details with a stacked bar chart with color coded legend!

**Comment by langswei** [comment]
Dashboard deprecated, closing issue.
