### ISSUE TITLE
UI feedback from Bryan

### ISSUE THREAD

**Issue by langswei** [adobe/franklin-dashboard#96]
@bstopp is using the dashboard and will share feedback on this issue.  I've captured two of his comments to start:
- domain key is plain text on the main login form but hidden/password on left filter - inconsistent
- sort by url does not work

cc: @MarquiseRosier

**Comment by bstopp** [comment]
On the Calendar - there should be a "Today" button, that takes you to today.

**Comment by langswei** [comment]
Dashboard deprecated, closing issue.
